Countdown in hours and minutes
bigshortbets/market-frontend pull request #32
Opened 2024-03-26 20:54 UTC by salalo

#22 calculate time left before market closes in different units
![1](https://github.com/bigshortbets/market-frontend/assets/23582955/d679818a-93a0-47a2-8b11-15705e637891)
![2](https://github.com/bigshortbets/market-frontend/assets/23582955/e8480596-a2a1-46b1-a44a-c24abe22e7f4)

2024-03-26 20:58 UTC, salalo commented
If you need `daysLeft: number` in the interface, just close. I saw that `daysLeft` was only used in one place to display the data.

2024-03-27 10:54 UTC, kacpergumieniuk commented
Thanks @salalo  for the pull request, I'll do some review and point out potential problems, so you can improve the solution

2024-03-27 11:39 UTC, kacpergumieniuk requested changes

2024-03-27 11:39 UTC, kacpergumieniuk commented on utils/calculateMarketClosing.ts
> +};
I think we got poor readability here. Below you got my proposition, where we just check if some condition is met, and if yes we just return actual message and end the function. You can give feedback about my idea or just implement it.
```
const calculateTimeLeft = (targetDate: Date): string => {
  const currentDate = new Date();
  const daysDifference = differenceInDays(targetDate, currentDate);

  if (daysDifference > 0) {
    return `${daysDifference} day${daysDifference > 1 ? "s" : ""} left`;
  }

  const hoursDifference = differenceInHours(targetDate, currentDate);
  if (hoursDifference > 0) {
    return `${hoursDifference} hour${hoursDifference > 1 ? "s" : ""} left`;
  }

  const minutesDifference = differenceInMinutes(targetDate, currentDate);
  if (minutesDifference > 0) {
    return `${minutesDifference} minute${minutesDifference > 1 ? "s" : ""} left`;
  }

  return "Market closed";
};

2024-03-27 11:39 UTC, kacpergumieniuk commented on utils/calculateMarketClosing.ts
>  };
I think we should keep main return of the function at the very bottom of it, so for being consistent, we should put it below calculateTimeLeft func

2024-03-27 11:39 UTC, kacpergumieniuk commented on utils/calculateMarketClosing.ts
> +};
and what really that function does, it's giving us time left message, not just calculating it so we can think of changing the name to getTimeLeftMessage

2024-03-27 11:39 UTC, kacpergumieniuk commented on utils/categorizeMarkets.ts
>  }
I think that we should change that prop from timeLeft to timeLeftMessage, as it's a message string, to keep the readability. Also, what you mentioned in your comment about keeping the daysLeft, i think we dont need it, but for future purposes of filtering markets by time, we should return some number representation of timeLeft.  Maybe we should just aslo return const diff = lifetime - blockHeight (called in some way of your choice, maybe timeDiff: number), to compare which market is older in the future?

2024-03-27 12:58 UTC, salalo commented on utils/calculateMarketClosing.ts
> +};
Yeah, you're right, I wanted to omit difference calculations when it's not necessary, thus the nesting, but returning early works as well and it's more readable, good one. 

Also agree with changing the function name.

2024-03-27 13:12 UTC, salalo commented
@kacpergumieniuk Btw, if you could add some formatting/linting config files it would be great, so it aligns all around the repo.

2024-03-27 13:23 UTC, kacpergumieniuk commented
> @kacpergumieniuk Btw, if you could add some formatting/linting config files it would be great, so it aligns all around the repo.

yeah gonna do that soon

2024-03-27 13:24 UTC, kacpergumieniuk approved these changes

2024-03-28 08:26 UTC, merged